### ISSUE TITLE
meetups

### ISSUE THREAD

**Issue by ghost** [agenda-tech-brasil/agenda-tech-brasil#183]

**Comment by stephan-lopes** [comment]
> como participo, colaboro ou elaboro meetups aqui?

Se a dúvida for relacionado a como ajudar nesse repo, adicionando um meetup que não viu ainda por aqui, basta fazer o seguinte:

1. Faz um Fork do Repositório.
2. Cria uma branch separada da main no seu fork (ex. patch-1).
3. Adicione no README.md o meetup, seguindo o padrão já definido nos outros eventos (o lint irá reclamar, caso não siga o padrão).
4. Abra um PR de sua branch no fork para a branch main desse repositório.

Após isso, aguarde o merge ;)
